  0%|          | 0/9912422 [00:00<?, ?it/s] 77%|███████▋  | 7677952/9912422 [00:00<00:00, 76774834.04it/s]9913344it [00:00, 85990123.64it/s]                             
  0%|          | 0/28881 [00:00<?, ?it/s]29696it [00:00, 88903677.08it/s]         
  0%|          | 0/1648877 [00:00<?, ?it/s]1649664it [00:00, 25640123.00it/s]         
  0%|          | 0/4542 [00:00<?, ?it/s]5120it [00:00, 28941828.14it/s]         
Traceback (most recent call last):
  File "/home/joe/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/joe/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/nni/retiarii/trial_entry.py", line 10, in <module>
    main()
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/nni/nas/execution/trial_entry.py", line 29, in main
    engine.trial_execute_graph()
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/nni/nas/execution/pytorch/simplified.py", line 72, in trial_execute_graph
    graph_data.evaluator._execute(_model)
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/nni/nas/evaluator/functional.py", line 37, in _execute
    return self.function(model_cls, **self.arguments)
  File "/tmp/ipykernel_464104/4216432585.py", line 58, in evaluate_model
  File "/tmp/ipykernel_464104/4216432585.py", line 14, in train_epoch
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/ipykernel_464104/1379045085.py", line 37, in forward
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/joe/.cache/pypoetry/virtualenvs/nas-test-OHy8kATa-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
